-- ============================================================================
-- Uninstall counterpart for 001_revert_2.3.0_creature_rank_and_hp.sql
--
-- TODO: Generate the reverse UPDATEs that restore TBC 2.4.3 stock values for
-- `Rank` and `HealthMultiplier` on the same 297 creatures the install file
-- modifies.
--
-- Source data needed for generation:
--   zzDocumentation/zzResearch/2.3.0/data/creature_rank_changes.csv
-- The CSV records each affected creature with both the vanilla and TBC values
-- for Rank and HealthMultiplier; this uninstall file should apply the TBC
-- (post-2.3.0) values, grouped into UPDATEs by (tbc_rank, tbc_HealthMultiplier)
-- the same way the install file groups by vanilla values.
-- ============================================================================
