#!/bin/bash
# Client-data extractor for cmangos-tbc.
#
# Mounts:
#   /client  — WoW 2.4.3 client install, read-only (provided by host)
#   /output  — writable volume that ends up at /cmangos/dist/data
#
# Pipeline: ad → vmap_extractor → vmap_assembler. mmaps are not generated by
# default (EXTRACT_MMAPS=1 to opt in).

set -euo pipefail

CLIENT=/client
OUT=/output
BIN=/cmangos/dist/bin/tools

: "${EXTRACT_MMAPS:=0}"

log() { echo "[extractor] $*"; }

if [[ ! -d "$CLIENT/Data" ]]; then
    log "ERROR: $CLIENT/Data missing — CM_CLIENT_DIR must point at a WoW 2.4.3 root (the folder with Wow.exe + Data/)"
    exit 1
fi

mkdir -p "$OUT"
cd "$OUT"

# Extractors expect Data/ in cwd. Symlink the client's Data into /output.
[[ -L Data ]] || ln -s "$CLIENT/Data" Data

if [[ -d dbc && -d maps ]]; then
    log "skip ad (Map+DBC): already populated"
else
    log "running ad (Map + DBC extractor)"
    "$BIN/ad"
fi

if [[ -d vmaps && -n "$(ls -A vmaps 2>/dev/null)" ]]; then
    log "skip VMaps: vmaps/ already populated"
else
    if [[ ! -d Buildings ]]; then
        log "running vmap_extractor → Buildings/"
        "$BIN/vmap_extractor" -d "$CLIENT/Data" -o "$OUT"
    fi
    log "running vmap_assembler → vmaps/"
    mkdir -p vmaps
    "$BIN/vmap_assembler" Buildings vmaps
fi

if [[ "$EXTRACT_MMAPS" == "1" ]]; then
    if [[ -d mmaps && -n "$(ls -A mmaps 2>/dev/null)" ]]; then
        log "skip mmaps: already populated"
    else
        log "generating mmaps (this takes a long time)"
        mkdir -p mmaps
        "$BIN/MoveMapGen"
    fi
fi

# Cleanup the working state
rm -f Data
rm -rf Buildings

log "done"
ls -la "$OUT"
